name: 'Auto merge dependency update'
on: pull_request
permissions:
  contents: write
  pull-requests: write
jobs:
  auto-merge:
    name: 'Auto merge'
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.repository_owner == 'EvaristeGalois11'
    steps:
      - name: 'Approve'
        run: gh pr review --approve "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
      - name: 'Merge'
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}