name: 'Build'
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: 'Verify project'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout project'
        uses: actions/checkout@v4

      - name: 'Set up Java 21'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: 'Build and test'
        run: ./mvnw -B install

      - name: 'Prepare Sonar analysis'
        uses: evaristegalois11/sonar-fork-analysis@master
