name: 'Build and deploy'
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: 'Verify project'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout project'
        uses: actions/checkout@v4

      - name: 'Set up Java 21'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: 'Build and test'
        run: ./mvnw -B verify

  deploy:
    name: 'Deploy to Github Container Registry'
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: 'Checkout project'
        uses: actions/checkout@v4

      - name: 'Set up Java 21'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: 'Login to Github Container Registry'
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: 'ghcr.io'

      - name: 'Deploy'
        run: ./mvnw -B compile jib:build
