name: 'Sonar'
on:
  workflow_run:
    workflows: [ Build ]
    types:
      - completed
jobs:
  sonar:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: write
      checks: write
    steps:
      - name: 'Set up JDK 21'
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: 'Execute Sonar analysis'
        uses: evaristegalois11/sonar-fork-analysis@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}